### ISSUE TITLE
Why the temperature is set to be 1?

### ISSUE THREAD

**Issue by Matt-Zhang** [okisdev/polish-sentences-popclip-ext#1]
According to the example provided by OpenAI and the doc, tasks like grammar check requires higher deterministic so the temperature should be set closed to 0. However, I also found 0.8 or 1 have better results. What's the reason for this?

**Comment by okisdev** [comment]
@Matt-Zhang Hi Matt,

High temperature produces more creative content than low temperature. It will not answer you based entirely on what AI trained (and 0 will do so to a large extent).

In addition, the low temperature gives less criticism to the AI, which results in the AI answering the question from the perspective of a superior student, so the resulting answer is better for the AI, but we do not think so.

In short, it is like facing the orientation of a student. If it is positioned as a superior student (low temperature), then it will have absolute confidence to answer your questions, and it will tacitly agree that the questions it answers are correct. And often intermediate students (around 1), will answer your questions with scepticism, and may question their own answers, in the continuous optimization of the answer will become more perfect.

Hope it helps.

**Comment by okisdev** [comment]
Please note that if there is no further conversation, this issue will be closed within 24 hours.
